
import "./globals.css";

export const metadata = {
  title: "Motion Wizz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preload" href="/DMSans-Regular.woff2" as="font" type="font/woff2"
          crossOrigin="anonymous" />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
